[package]
name = "stacks-common"
version = "0.0.1"
authors = [
    "Jude Nelson <jude@stacks.org>",
    "Aaron Blankstein <aaron@blockstack.com>",
    "Ludo Galabru <ludovic@blockstack.com>",
]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Common modules for blockstack_lib, libclarity"
keywords = [
    "stacks",
    "stx",
    "bitcoin",
    "crypto",
    "blockstack",
    "decentralized",
    "dapps",
    "blockchain",
]
readme = "README.md"
resolver = "2"
edition = "2021"
build = "build.rs"

[lib]
name = "stacks_common"
path = "./src/libcommon.rs"

[dependencies]
rand = { workspace = true }
serde = { workspace = true , features = ["derive"] }
serde_derive = { workspace = true }
sha3 = "0.10.1"
ripemd = "0.1.1"
lazy_static = { workspace = true }
slog = { workspace = true }
slog-term = "2.6.0"
slog-json = { version = "2.3.0", optional = true }
chrono = "0.4.19"
hashbrown = { workspace = true }
rusqlite = { workspace = true, optional = true }

[target.'cfg(unix)'.dependencies]
nix = {version = "0.23", optional = true}

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "consoleapi",
    "handleapi",
    "synchapi",
    "winbase",
] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["fileapi", "processenv", "winnt"] }

[dependencies.serde_json]
version = "1.0"
features = ["arbitrary_precision", "unbounded_depth"]

[dependencies.ed25519-dalek]
workspace = true

[dependencies.curve25519-dalek]
version = "4.1.3"
features = ["serde"]

[dependencies.time]
version = "0.2.23"
features = ["std"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
secp256k1 = { version = "0.24.3", features = ["serde", "recovery"] }

[target.'cfg(target_family = "wasm")'.dependencies]
libsecp256k1 = { version = "0.7.0" }

[dev-dependencies]
rand_core = { workspace = true }
proptest = "1.6.0"

[features]
default = ["developer-mode", "ctrlc-handler", "http-parser"]
developer-mode = []
ctrlc-handler = ["dep:nix"]
http-parser = []
slog_json = ["slog-json"]
rusqlite = ["dep:rusqlite"]
testing = []
serde = []
bech32_std = []
bech32_strict = []

[build-dependencies]
toml = { workspace = true }

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(any(target_os="windows"))))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), any(target_os="windows")))'.dependencies]
sha2 = { version = "0.10" }
