name: Seed Caches

################################################################################################################################
# GitHub caches are scoped to branches, with a fallback mechanism:
#   1. A branch can only see caches created on that branch
#   2. Failing that, a branch can opt-in to looking at the base branch cache
#   3. Failing that, a branch can always access the default branch caches (`main` or `master`)
# So we build caches on `master` nightly, since our branches typically target `develop` as base (and can fallback to `master`)
# That allows PR branches to re-use these caches, via `restore-keys` fallback in the actions/cache GitHub action
# The cache cache is intentionally broad: it will restore what `master` currently has.
# If the branch has updated dependencies, cargo will notice the mismatched versions (or new deps) and build them on-the-fly.
################################################################################################################################

on:
  schedule:
    # Run at 12am Eastern Time every day
    - cron: '0 0 * * *'
      timezone: 'America/New_York'
  workflow_dispatch: # Allows manual triggering / seeding

permissions:
  contents: read

# Configure concurrency
#   - cache will exist longer than workflow execution so other runners have access.
#   - this must be atomic and never run in parallel
concurrency:
  group: seed-caches
  cancel-in-progress: false

jobs:
  # Check which caches already exist before creating them
  check-caches:
    name: Check Existing Caches
    # Only execute if running in our core repo, the CRON will run against `master` which is intended
    if: |
      github.repository == 'stacks-network/stacks-core'
    runs-on: ubuntu-latest
    outputs:
      bitcoin-cache-hit: ${{ steps.bitcoin.outputs.cache-hit }}
      cargo-cache-hit: ${{ steps.cargo.outputs.cache-hit }}
    steps:
      # Checkout the code
      #   - only .github is required for checking caches
      - name: Checkout the latest code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github
    
      # Check cache for bitcoin binary
      - name: Check Bitcoin Cache
        id: bitcoin
        uses: ./.github/actions/cache/bitcoin

      # Check cache for cargo binaries
      - name: Check Cargo Cache
        id: cargo
        uses: ./.github/actions/cache/cargo

      # Output a job summary of cache status
      - name: Output GitHub Job Summary
        shell: bash
        run: |
          echo "## Cache Status" >> $GITHUB_STEP_SUMMARY
          echo "| Cache | Cache Key | Exists? |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Bitcoin | ${{ steps.bitcoin.outputs.cache-key }} | ${{ steps.bitcoin.outputs.cache-hit == 'true' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Cargo | ${{ steps.cargo.outputs.cache-key }} | ${{ steps.cargo.outputs.cache-hit == 'true' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY

  # Cache the bitcoin binary (if it doesn't exist)
  cache-bitcoin-binary:
    name: Build & Cache Bitcoin Binary
    needs:
      - check-caches
    runs-on: ubuntu-latest
    if: needs.check-caches.outputs.bitcoin-cache-hit != 'true'
    steps:
      # Checkout the code
      #   - only .github is required for checking caches
      - name: Checkout the latest code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      - name: Create Bitcoin Cache
        uses: ./.github/actions/cache/bitcoin
        with:
          action: create

  # Cache the cargo crates (if they don't exist)
  cache-cargo:
    name: Build & Cache Cargo Crates
    needs:
      - check-caches
    runs-on: ubuntu-latest
    if: needs.check-caches.outputs.cargo-cache-hit != 'true'
    steps:
      # Checkout the code
      #   - only .github is required for checking caches
      - name: Checkout the latest code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      - name: Create Cargo Cache
        uses: ./.github/actions/cache/cargo
        with:
          action: create
