## Perform Clippy checks - currently set to defaults
##   https://github.com/rust-lang/rust-clippy#usage
##   https://rust-lang.github.io/rust-clippy/master/index.html
##
name: Clippy Checks

# Only run when:
#   - PRs are (re)opened against develop branch
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize

jobs:
  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Clippy
        id: clippy
        uses: actions-rs/clippy-check@v1
        with:
          alias: "clippy-stacks"